//! Single-Contract Isolated Implementation Probe (docs/contract-readiness-assessment.md, Q5).
//!
//! Experiment name:  Mandatory/optional signal sufficiency probe
//! Inputs:           Two real, mechanically-derivable unit contracts from manufacturer-001's
//!                    actual entity schema — `ManufacturerNameValidation` (mandatory field,
//!                    min_length: 1) and `ManufacturerPhoneNumberValidation` (optional field,
//!                    min_length: 0 — vacuous, so no lower-bound behavior exists at all) — plus
//!                    the Spring Boot "model" layer skill. No story, no spec, no ADRs, no other
//!                    fields, no scenario list.
//! Success criteria: The model correctly infers "name" requires a non-empty value (the only
//!                    signal available is the "shorter than 1 characters is rejected" prose) AND
//!                    correctly leaves "phoneNumber" nullable/optional (no lower-bound behavior
//!                    exists in its contract at all, so nothing implies it's mandatory).
//! Failure modes:    The model marks phoneNumber as mandatory anyway (a natural default absent
//!                    an explicit optional signal), or fails to infer name's non-blank
//!                    requirement from the min_length prose alone.
//! Expected learning: Whether Contract's remaining open gap (Q3's third blocker — no explicit
//!                    mandatory/optional field) is genuinely load-bearing, or whether the prose
//!                    in `required_tests` already carries enough signal in practice.
//!
//! The two Contract/Behavior values below are not generated by calling the mechanical pipeline
//! (`mechanical_validation_behaviors` etc. are private to canopy-llm) — they're hand-constructed
//! to exactly match what that pipeline produces for these two real fields, already verified by
//! this project's own unit tests (see `unit_validation_contract_carries_kind_entity_and_member`
//! in canopy-llm/src/prompts/contracts.rs) and by this assessment's own Q3 hand-trace. Building
//! them here only replays already-verified mechanical output as a fixture, not new derivation.
//!
//! Run against a local llama-server (matches this project's dogfooding model):
//!   cargo run -p canopy-llm --example contract_isolation_probe

use canopy_core::{AgentLlmConfig, LlmProvider};
use canopy_llm::{skill_for_technology, LlmClient};

struct ProbeContract {
    label: &'static str,
    entity: &'static str,
    member: &'static str,
    required_tests: &'static [&'static str],
}

fn probe_prompt(contract: &ProbeContract, tech_rules: &str) -> String {
    format!(
        "You are implementing exactly one field of a Java JPA entity class, using ONLY the \
         information below — do not assume any requirement not explicitly stated here.\n\
         \n\
         Entity: {entity}\n\
         Field: {member}\n\
         Kind: Validation\n\
         \n\
         Required behavior (verbatim — the only source of truth for what this field must do):\n\
         {tests}\n\
         \n\
         {tech_rules}\n\
         \n\
         Write ONLY the field declaration and its Bean Validation annotations for `{member}` — \
         not the whole class, not other fields, not a constructor.\n",
        entity = contract.entity,
        member = contract.member,
        tests = contract.required_tests.iter().map(|t| format!("- \"{t}\"")).collect::<Vec<_>>().join("\n"),
        tech_rules = tech_rules,
    )
}

fn main() {
    let contracts = [
        ProbeContract {
            label: "ManufacturerNameValidation (mandatory field — min_length: 1)",
            entity: "Manufacturer",
            member: "name",
            required_tests: &[
                "Name longer than 200 characters is rejected.",
                "Name shorter than 1 characters is rejected.",
            ],
        },
        ProbeContract {
            label: "ManufacturerPhoneNumberValidation (optional field — min_length: 0, vacuous, no lower-bound behavior at all)",
            entity: "Manufacturer",
            member: "phoneNumber",
            required_tests: &[
                "Phone number longer than 20 characters is rejected.",
            ],
        },
    ];

    let client = LlmClient::from_agent_config(
        &AgentLlmConfig {
            provider: LlmProvider::Ollama,
            model: "qwen2.5-coder:14b".to_string(),
            base_url: Some("http://localhost:8080".to_string()),
        },
        false,
    );

    let tech_rules = skill_for_technology("Spring Boot", "com.example.manufacturer", "com/example/manufacturer", "manufacturer-service", "model");

    for contract in &contracts {
        println!("=== {} ===\n", contract.label);
        let prompt = probe_prompt(contract, &tech_rules);
        match client.complete(&prompt) {
            Ok(response) => println!("{response}\n"),
            Err(e) => println!("LLM call failed: {e}\n"),
        }
        println!("----------------------------------------\n");
    }
}
